name: CI

on:
  schedule:
    - cron: '0 0 10 * *' # 日本時間 (JST): 毎月10日 09:00（UTC 00:00）
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.2.0
        with:
          pattern: '*.json'
